name: lesnar-ai-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  # CUDA-enabled PyTorch stack
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  # Core scientific stack (via conda for stability)
  - numpy>=1.24,<2.0
  - matplotlib>=3.7
  # Remaining packages via pip (excluding torch/torchvision to avoid duplicates)
  - pip:
      - opencv-python>=4.8
      - pandas>=2.1,<2.4
      - tqdm>=4.66
      - PyYAML>=6.0
      - scikit-image>=0.22
      - albumentations>=1.4
      - tensorboard>=2.14,<2.16
      - einops>=0.7
      - gymnasium>=1.2,<1.3
      - stable-baselines3>=2.7,<2.8
      - airsim>=1.8.1
      - mavsdk>=1.6
      - typing-extensions>=4.9
